import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { KindeProvider } from "@kinde-oss/kinde-auth-nextjs";
import { AuthProvider } from "@/components/shared/AuthProvider";
const VietnamPro = Be_Vietnam_Pro({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-vietnam-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: `The King Barber`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-AR">
      <body className={`${VietnamPro.variable} antialiased bg-[#231a10]`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
